export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "hy", name: "Հայերեն (Armenian)", flag: "🇦🇲" },
  { code: "en", name: "English (English)", flag: "🇬🇧" },
  { code: "ru", name: "Русский (Russian)", flag: "🇷🇺" },
  { code: "es", name: "Español (Spanish)", flag: "🇪🇸" },
  { code: "fr", name: "Français (French)", flag: "🇫🇷" },
  { code: "de", name: "Deutsch (German)", flag: "🇩🇪" },
  { code: "it", name: "Italiano (Italian)", flag: "🇮🇹" },
  { code: "pt", name: "Português (Portuguese)", flag: "🇵🇹" },
  { code: "zh", name: "中文 (Chinese)", flag: "🇨🇳" },
  { code: "ja", name: "日本語 (Japanese)", flag: "🇯🇵" },
  { code: "ko", name: "한국어 (Korean)", flag: "🇰🇷" },
  { code: "ar", name: "العربية (Arabic)", flag: "🇸🇦" },
  { code: "fa", name: "فارسی (Persian)", flag: "🇮🇷" },
  { code: "tr", name: "Türkçe (Turkish)", flag: "🇹🇷" },
  { code: "ka", name: "ქართული (Georgian)", flag: "🇬🇪" },
  { code: "el", name: "Ελληνικά (Greek)", flag: "🇬🇷" },
  { code: "pl", name: "Polski (Polish)", flag: "🇵🇱" },
  { code: "nl", name: "Nederlands (Dutch)", flag: "🇳🇱" },
  { code: "uk", name: "Українська (Ukrainian)", flag: "🇺🇦" },
  { code: "he", name: "עברית (Hebrew)", flag: "🇮🇱" },
  { code: "hi", name: "हिन्दी (Hindi)", flag: "🇮🇳" },
  { code: "la", name: "Latina (Latin)", flag: "🇻🇦" },
  { code: "eo", name: "Esperanto (Esperanto)", flag: "🌐" },
  { code: "sv", name: "Svenska (Swedish)", flag: "🇸🇪" },
  { code: "no", name: "Norsk (Norwegian)", flag: "🇳🇴" },
  { code: "da", name: "Dansk (Danish)", flag: "🇩🇰" },
  { code: "fi", name: "Suomi (Finnish)", flag: "🇫🇮" },
  { code: "cs", name: "Čeština (Czech)", flag: "🇨🇿" },
  { code: "hu", name: "Magyar (Hungarian)", flag: "🇭🇺" },
  { code: "ro", name: "Română (Romanian)", flag: "🇷🇴" },
  { code: "bg", name: "Български (Bulgarian)", flag: "🇧🇬" },
  { code: "id", name: "Bahasa Indonesia (Indonesian)", flag: "🇮🇩" },
  { code: "ms", name: "Bahasa Melayu (Malay)", flag: "🇲🇾" },
  { code: "th", name: "ไทย (Thai)", flag: "🇹🇭" },
  { code: "vi", name: "Tiếng Việt (Vietnamese)", flag: "🇻🇳" },
  { code: "tl", name: "Tagalog (Filipino)", flag: "🇵🇭" },
  { code: "sw", name: "Kiswahili (Swahili)", flag: "🇰🇪" },
  { code: "af", name: "Afrikaans (Afrikaans)", flag: "🇿🇦" },
  { code: "am", name: "አማርኛ (Amharic)", flag: "🇪🇹" },
  { code: "az", name: "Azərbaycanca (Azerbaijani)", flag: "🇦🇿" },
  { code: "be", name: "Беларуская (Belarusian)", flag: "🇧🇾" },
  { code: "bn", name: "বাংলা (Bengali)", flag: "🇧🇩" },
  { code: "bs", name: "Bosanski (Bosnian)", flag: "🇧🇦" },
  { code: "ca", name: "Català (Catalan)", flag: "🇪🇸" },
  { code: "cy", name: "Cymraeg (Welsh)", flag: "🇬🇧" },
  { code: "et", name: "Eesti (Estonian)", flag: "🇪🇪" },
  { code: "eu", name: "Euskara (Basque)", flag: "🇪🇸" },
  { code: "ga", name: "Gaeilge (Irish)", flag: "🇮🇪" },
  { code: "gl", name: "Galego (Galician)", flag: "🇪🇸" },
  { code: "gu", name: "ગુજરાતી (Gujarati)", flag: "🇮🇳" },
  { code: "ha", name: "Hausa (Hausa)", flag: "🇳🇬" },
  { code: "hr", name: "Hrvatski (Croatian)", flag: "🇭🇷" },
  { code: "ht", name: "Kreyòl Ayisyen (Haitian Creole)", flag: "🇭🇹" },
  { code: "hy", name: "Հայերեն (Armenian)", flag: "🇦🇲" },
  { code: "is", name: "Íslenska (Icelandic)", flag: "🇮🇸" },
  { code: "jw", name: "Javanese (Javanese)", flag: "🇮🇩" },
  { code: "kk", name: "Қазақ тілі (Kazakh)", flag: "🇰🇿" },
  { code: "km", name: "ខ្មែរ (Khmer)", flag: "🇰🇭" },
  { code: "kn", name: "ಕನ್ನಡ (Kannada)", flag: "🇮🇳" },
  { code: "ky", name: "Кыргызча (Kyrgyz)", flag: "🇰🇬" },
  { code: "lt", name: "Lietuvių (Lithuanian)", flag: "🇱🇹" },
  { code: "lv", name: "Latviešu (Latvian)", flag: "🇱🇻" },
  { code: "mk", name: "Македонски (Macedonian)", flag: "🇲🇰" },
  { code: "ml", name: "മലയാളം (Malayalam)", flag: "🇮🇳" },
  { code: "mn", name: "Монгол (Mongolian)", flag: "🇲🇳" },
  { code: "mr", name: "मराठी (Marathi)", flag: "🇮🇳" },
  { code: "mt", name: "Malti (Maltese)", flag: "🇲🇹" },
  { code: "my", name: "မြန်မာ (Burmese)", flag: "🇲🇲" },
  { code: "ne", name: "नेपाली (Nepali)", flag: "🇳🇵" },
  { code: "pa", name: "ਪੰਜਾਬੀ (Punjabi)", flag: "🇮🇳" },
  { code: "si", name: "සිංහල (Sinhala)", flag: "🇱🇰" },
  { code: "sk", name: "Slovenčina (Slovak)", flag: "🇸🇰" },
  { code: "sl", name: "Slovenščina (Slovenian)", flag: "🇸🇮" },
  { code: "sq", name: "Shqip (Albanian)", flag: "🇦🇱" },
  { code: "sr", name: "Српски (Serbian)", flag: "🇷🇸" },
  { code: "ta", name: "தமிழ் (Tamil)", flag: "🇮🇳" },
  { code: "te", name: "తెలుగు (Telugu)", flag: "🇮🇳" },
  { code: "tg", name: "Тоҷикӣ (Tajik)", flag: "🇹🇯" },
  { code: "ur", name: "اردو (Urdu)", flag: "🇵🇰" },
  { code: "uz", name: "O'zbekcha (Uzbek)", flag: "🇺🇿" },
  { code: "yi", name: "ייִדיש (Yiddish)", flag: "🇮🇱" },
  { code: "yo", name: "Yorùbá (Yoruba)", flag: "🇳🇬" },
  { code: "zu", name: "isiZulu (Zulu)", flag: "🇿🇦" }
];
