#!/usr/bin/env python3
"""
Generate per-language UI translation files for the AWESchool i18n system.

For top ~30 languages we provide hand-curated translations.
For the remaining 220+ languages we generate a file that imports English and
defers to Google Translate API at runtime (the fallback template).

Output: /home/z/my-project/src/lib/i18n/translations/<code>.ts
"""

import os
import json
from pathlib import Path

OUT_DIR = Path("/home/z/my-project/src/lib/i18n/translations")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Hand-curated translations for top languages.
# Each dict MUST contain the same keys as hy.ts (the source file).
# ---------------------------------------------------------------------------

TRANSLATIONS = {
    "en": {
        "app.title": "World of Knowledge",
        "app.subtitle": "AWESchool - Educational Game",
        "welcome.title": "Welcome",
        "welcome.name_placeholder": "Enter your name",
        "welcome.start": "Start Learning",
        "welcome.new_user": "New Registration",
        "welcome.restore": "I already have an account — Restore",
        "welcome.desc": "Interactive educational platform: 200+ subjects, 10,000+ lessons, voice reading, exams.",
        "welcome.restore_file": "Restore from JSON file",
        "welcome.choose_avatar": "Choose your character",
        "home.greeting": "Welcome",
        "home.subtitle": "Choose a subject, learn lessons, pass exams",
        "subjects.core": "Core Subjects",
        "subjects.science": "Sciences",
        "subjects.language": "Humanities",
        "subjects.computer": "Computer Professions",
        "subjects.advanced": "Advanced Technologies",
        "lesson.listen": "Listen",
        "lesson.stop": "Stop",
        "lesson.next": "Next",
        "lesson.prev": "Previous",
        "lesson.start_exam": "Start Exam",
        "lesson.lessons": "lessons",
        "lesson.completed": "completed",
        "lesson.hint": "Get a hint",
        "lesson.explanation": "Explanation",
        "exam.question": "Question",
        "exam.check": "Check",
        "exam.exit": "Exit",
        "exam.congrats": "Congratulations",
        "exam.retry": "Try again",
        "exam.passed": "You successfully passed the exam",
        "exam.need_60": "Need 60%+ for the next lesson",
        "stats.lessons": "Completed Lessons",
        "stats.streak": "Day Streak",
        "stats.points": "Points",
        "stats.title": "My Statistics",
        "stats.achievements": "Achievements",
        "stats.study_time": "Studied",
        "stats.favorites": "Favorites",
        "stats.bookmarks": "Bookmarks",
        "settings.title": "Settings",
        "settings.theme": "Theme",
        "settings.theme_light": "Light",
        "settings.theme_dark": "Dark",
        "settings.theme_auto": "Auto",
        "settings.font_size": "Font Size",
        "settings.font_small": "Small",
        "settings.font_medium": "Medium",
        "settings.font_large": "Large",
        "settings.daily_goal": "Daily Goal",
        "settings.language": "Language",
        "settings.learning_mode": "Default learning mode",
        "settings.tip": "Dark theme is better for evening study. Large font for vision.",
        "mode.school": "School",
        "mode.university": "University",
        "mode.school_desc": "Easy lessons, colorful and interactive",
        "mode.university_desc": "Detailed book, 100+ pages, with tests",
        "guides.title": "Guides",
        "guides.how_to_use": "How to use the site",
        "guides.start": "How to start",
        "guides.start_desc": "First steps on the site",
        "guides.modes": "School and University",
        "guides.modes_desc": "Two learning modes",
        "guides.listen": "Listen to lessons",
        "guides.listen_desc": "Voice reading",
        "guides.share": "Share statistics",
        "guides.share_desc": "Send your progress to friends",
        "guides.export": "Export / Import",
        "guides.export_desc": "File-based data backup",
        "guides.languages": "200+ languages",
        "guides.languages_desc": "Change site language",
        "guides.achievements": "Achievements",
        "guides.achievements_desc": "Compete with other participants",
        "guides.all_guides": "All guides",
        "guides.main": "Home",
        "guides.live_demo": "Live demo",
        "guides.step": "Step",
        "export": "EXPORT",
        "import": "IMPORT",
        "profile.title": "My Profile",
        "profile.share": "Share Profile",
        "search.placeholder": "Search lessons...",
        "filter.all": "All",
        "filter.completed": "Completed",
        "filter.available": "Available",
        "filter.locked": "Locked",
        "filter.favorites": "Favorites",
        "daily_goal": "Daily Goal",
        "recently_viewed": "Recently Viewed",
        "continue_learning": "Continue Learning",
        "reset": "Start Over",
        "share_data": "Share Data",
        "back_to_subjects": "Subjects",
        "my_achievements": "My achievements",
        "confirm_reset": "Are you sure you want to delete all progress?",
        "daily_goal_done": "🎉 Congratulations! Today's goal is achieved!",
        "daily_goal_remaining": "{n} lessons left to reach today's goal",
        "university.book_title": "Book",
        "university.chapter": "Chapter",
        "university.page": "Page",
        "university.test": "Test",
        "university.pass_threshold": "Pass threshold: 51%",
        "university.next_chapter": "Next Chapter",
        "footer.copyright": "© AWESchool All rights reserved",
        "footer.tagline": "Learn, play, grow",
        "share.summary": "Statistics",
        "share.completed_lessons": "Completed lessons",
        "share.streak": "Day streak",
        "share.points": "Points",
        "share.achievements": "Achievements",
        "share.total_lessons": "Total lessons",
        "share.study_time": "Study time",
        "share.creating": "Creating screenshot...",
        "share.copied": "Statistics copied!",
        "share.button": "Share statistics",
        "tts.working": "Voice works via Google TTS",
        "tts.engine": "Current engine",
        "tts.test_voice": "Test voice",
        "tts.select_voice": "Select voice",
        "tts.speed": "Speed",
        "tts.pitch": "Pitch",
        "tts.volume": "Volume",
        "tts.info": "Text is read by Google TTS (free)",
        "file.export_title": "Data export / import",
        "file.export_desc": "Download all your data as a signed JSON file",
        "file.import_desc": "Restore your data from a previously exported file",
        "file.protected": "Files are signed by AWESchool. Forged files will be rejected.",
        "file.warning": "Import will replace current data.",
        "file.exported": "Data exported (signed file)",
        "file.imported": "Data successfully imported from file!",
        "file.invalid": "Invalid file format",
        "file.read_error": "Failed to read file",
        "lang.changed": "Language changed",
        "lang.select": "Select language",
        "lang.search": "Search language...",
        "lang.no_results": "No results found",
    },
    "ru": {
        "app.title": "Мир Знаний",
        "app.subtitle": "AWESchool - Образовательная Игра",
        "welcome.title": "Добро пожаловать",
        "welcome.name_placeholder": "Введите ваше имя",
        "welcome.start": "Начать обучение",
        "welcome.new_user": "Новая регистрация",
        "welcome.restore": "У меня уже есть аккаунт — Восстановить",
        "welcome.desc": "Интерактивная образовательная платформа: 200+ предметов, 10 000+ уроков, чтение голосом, экзамены.",
        "welcome.restore_file": "Восстановить из JSON файла",
        "welcome.choose_avatar": "Выбери своего персонажа",
        "home.greeting": "Добро пожаловать",
        "home.subtitle": "Выберите предмет, изучайте уроки, сдавайте экзамены",
        "subjects.core": "Основные предметы",
        "subjects.science": "Науки",
        "subjects.language": "Гуманитарные предметы",
        "subjects.computer": "Компьютерные профессии",
        "subjects.advanced": "Передовые технологии",
        "lesson.listen": "Слушать",
        "lesson.stop": "Стоп",
        "lesson.next": "Далее",
        "lesson.prev": "Назад",
        "lesson.start_exam": "Начать экзамен",
        "lesson.lessons": "уроков",
        "lesson.completed": "завершено",
        "lesson.hint": "Получить подсказку",
        "lesson.explanation": "Объяснение",
        "exam.question": "Вопрос",
        "exam.check": "Проверить",
        "exam.exit": "Выход",
        "exam.congrats": "Поздравляем",
        "exam.retry": "Попробуйте снова",
        "exam.passed": "Вы успешно сдали экзамен",
        "exam.need_60": "Нужно 60%+ для следующего урока",
        "stats.lessons": "Завершённых уроков",
        "stats.streak": "Дней подряд",
        "stats.points": "Очки",
        "stats.title": "Моя статистика",
        "stats.achievements": "Достижения",
        "stats.study_time": "Изучено",
        "stats.favorites": "Избранное",
        "stats.bookmarks": "Закладки",
        "settings.title": "Настройки",
        "settings.theme": "Тема",
        "settings.theme_light": "Светлая",
        "settings.theme_dark": "Тёмная",
        "settings.theme_auto": "Авто",
        "settings.font_size": "Размер шрифта",
        "settings.font_small": "Маленький",
        "settings.font_medium": "Средний",
        "settings.font_large": "Большой",
        "settings.daily_goal": "Дневная цель",
        "settings.language": "Язык",
        "settings.learning_mode": "Основной режим обучения",
        "settings.tip": "Тёмная тема удобнее для вечернего обучения. Крупный шрифт для зрения.",
        "mode.school": "Школьный",
        "mode.university": "Университетский",
        "mode.school_desc": "Лёгкие уроки, красочный и интерактивный",
        "mode.university_desc": "Подробная книга, 100+ страниц, с тестами",
        "guides.title": "Руководства",
        "guides.how_to_use": "Как пользоваться сайтом",
        "guides.start": "Как начать",
        "guides.start_desc": "Первые шаги на сайте",
        "guides.modes": "Школьный и Университетский",
        "guides.modes_desc": "Два режима обучения",
        "guides.listen": "Слушать уроки",
        "guides.listen_desc": "Чтение голосом",
        "guides.share": "Поделиться статистикой",
        "guides.share_desc": "Отправьте свой прогресс друзьям",
        "guides.export": "Экспорт / Импорт",
        "guides.export_desc": "Сохранение данных в файл",
        "guides.languages": "200+ языков",
        "guides.languages_desc": "Изменить язык сайта",
        "guides.achievements": "Достижения",
        "guides.achievements_desc": "Соревнуйтесь с другими участниками",
        "guides.all_guides": "Все руководства",
        "guides.main": "Главная",
        "guides.live_demo": "Живая демонстрация",
        "guides.step": "Шаг",
        "export": "ЭКСПОРТ",
        "import": "ИМПОРТ",
        "profile.title": "Мой профиль",
        "profile.share": "Поделиться профилем",
        "search.placeholder": "Поиск уроков...",
        "filter.all": "Все",
        "filter.completed": "Завершённые",
        "filter.available": "Доступные",
        "filter.locked": "Заблокированные",
        "filter.favorites": "Избранное",
        "daily_goal": "Дневная цель",
        "recently_viewed": "Недавно просмотренные",
        "continue_learning": "Продолжить обучение",
        "reset": "Начать заново",
        "share_data": "Поделиться данными",
        "back_to_subjects": "Предметы",
        "my_achievements": "Мои достижения",
        "confirm_reset": "Вы уверены, что хотите удалить весь прогресс?",
        "daily_goal_done": "🎉 Поздравляем! Цель на сегодня достигнута!",
        "daily_goal_remaining": "Осталось {n} уроков до цели",
        "university.book_title": "Книга",
        "university.chapter": "Глава",
        "university.page": "Страница",
        "university.test": "Тест",
        "university.pass_threshold": "Проходной балл: 51%",
        "university.next_chapter": "Следующая глава",
        "footer.copyright": "© AWESchool Все права защищены",
        "footer.tagline": "Учись, играй, развивайся",
        "share.summary": "Статистика",
        "share.completed_lessons": "Завершённых уроков",
        "share.streak": "Дней подряд",
        "share.points": "Очки",
        "share.achievements": "Достижения",
        "share.total_lessons": "Всего уроков",
        "share.study_time": "Время учёбы",
        "share.creating": "Создаётся скриншот...",
        "share.copied": "Статистика скопирована!",
        "share.button": "Поделиться статистикой",
        "tts.working": "Голос работает через Google TTS",
        "tts.engine": "Текущий движок",
        "tts.test_voice": "Проверить голос",
        "tts.select_voice": "Выбрать голос",
        "tts.speed": "Скорость",
        "tts.pitch": "Высота голоса",
        "tts.volume": "Громкость",
        "tts.info": "Текст читается через Google TTS (бесплатно)",
        "file.export_title": "Экспорт / импорт данных",
        "file.export_desc": "Скачайте все данные в подписанном JSON файле",
        "file.import_desc": "Восстановите данные из ранее экспортированного файла",
        "file.protected": "Файлы подписаны AWESchool. Поддельные файлы не принимаются.",
        "file.warning": "Импорт заменит текущие данные.",
        "file.exported": "Данные экспортированы (подписанный файл)",
        "file.imported": "Данные успешно импортированы из файла!",
        "file.invalid": "Неверный формат файла",
        "file.read_error": "Не удалось прочитать файл",
        "lang.changed": "Язык изменён",
        "lang.select": "Выбрать язык",
        "lang.search": "Поиск языка...",
        "lang.no_results": "Результаты не найдены",
    },
    "es": {
        "app.title": "Mundo del Conocimiento",
        "app.subtitle": "AWESchool - Juego Educativo",
        "welcome.title": "Bienvenido",
        "welcome.name_placeholder": "Ingresa tu nombre",
        "welcome.start": "Empezar a aprender",
        "welcome.new_user": "Nuevo registro",
        "welcome.restore": "Ya tengo cuenta — Restaurar",
        "welcome.desc": "Plataforma educativa interactiva: 200+ materias, 10.000+ lecciones, lectura por voz, exámenes.",
        "welcome.restore_file": "Restaurar desde archivo JSON",
        "welcome.choose_avatar": "Elige tu personaje",
        "home.greeting": "Bienvenido",
        "home.subtitle": "Elige una materia, aprende lecciones, aprueba exámenes",
        "subjects.core": "Materias principales",
        "subjects.science": "Ciencias",
        "subjects.language": "Humanidades",
        "subjects.computer": "Profesiones informáticas",
        "subjects.advanced": "Tecnologías avanzadas",
        "lesson.listen": "Escuchar",
        "lesson.stop": "Detener",
        "lesson.next": "Siguiente",
        "lesson.prev": "Anterior",
        "lesson.start_exam": "Comenzar examen",
        "lesson.lessons": "lecciones",
        "lesson.completed": "completado",
        "lesson.hint": "Obtener pista",
        "lesson.explanation": "Explicación",
        "exam.question": "Pregunta",
        "exam.check": "Comprobar",
        "exam.exit": "Salir",
        "exam.congrats": "¡Felicidades!",
        "exam.retry": "Intentar de nuevo",
        "exam.passed": "Aprobaste el examen exitosamente",
        "exam.need_60": "Necesitas 60%+ para la siguiente lección",
        "stats.lessons": "Lecciones completadas",
        "stats.streak": "Días consecutivos",
        "stats.points": "Puntos",
        "stats.title": "Mis estadísticas",
        "stats.achievements": "Logros",
        "stats.study_time": "Estudiado",
        "stats.favorites": "Favoritos",
        "stats.bookmarks": "Marcadores",
        "settings.title": "Ajustes",
        "settings.theme": "Tema",
        "settings.theme_light": "Claro",
        "settings.theme_dark": "Oscuro",
        "settings.theme_auto": "Auto",
        "settings.font_size": "Tamaño de fuente",
        "settings.font_small": "Pequeño",
        "settings.font_medium": "Mediano",
        "settings.font_large": "Grande",
        "settings.daily_goal": "Meta diaria",
        "settings.language": "Idioma",
        "settings.learning_mode": "Modo de aprendizaje predeterminado",
        "settings.tip": "El tema oscuro es mejor para estudiar de noche. Fuente grande para la vista.",
        "mode.school": "Escolar",
        "mode.university": "Universitario",
        "mode.school_desc": "Lecciones fáciles, colorido e interactivo",
        "mode.university_desc": "Libro detallado, 100+ páginas, con pruebas",
        "guides.title": "Guías",
        "guides.how_to_use": "Cómo usar el sitio",
        "guides.start": "Cómo empezar",
        "guides.start_desc": "Primeros pasos en el sitio",
        "guides.modes": "Escolar y Universitario",
        "guides.modes_desc": "Dos modos de aprendizaje",
        "guides.listen": "Escuchar lecciones",
        "guides.listen_desc": "Lectura por voz",
        "guides.share": "Compartir estadísticas",
        "guides.share_desc": "Envía tu progreso a amigos",
        "guides.export": "Exportar / Importar",
        "guides.export_desc": "Copia de seguridad basada en archivos",
        "guides.languages": "200+ idiomas",
        "guides.languages_desc": "Cambiar idioma del sitio",
        "guides.achievements": "Logros",
        "guides.achievements_desc": "Compite con otros participantes",
        "guides.all_guides": "Todas las guías",
        "guides.main": "Inicio",
        "guides.live_demo": "Demostración en vivo",
        "guides.step": "Paso",
        "export": "EXPORTAR",
        "import": "IMPORTAR",
        "profile.title": "Mi perfil",
        "profile.share": "Compartir perfil",
        "search.placeholder": "Buscar lecciones...",
        "filter.all": "Todos",
        "filter.completed": "Completados",
        "filter.available": "Disponibles",
        "filter.locked": "Bloqueados",
        "filter.favorites": "Favoritos",
        "daily_goal": "Meta diaria",
        "recently_viewed": "Vistos recientemente",
        "continue_learning": "Continuar aprendiendo",
        "reset": "Empezar de nuevo",
        "share_data": "Compartir datos",
        "back_to_subjects": "Materias",
        "my_achievements": "Mis logros",
        "confirm_reset": "¿Seguro que quieres borrar todo el progreso?",
        "daily_goal_done": "🎉 ¡Felicidades! ¡Meta de hoy cumplida!",
        "daily_goal_remaining": "Faltan {n} lecciones para la meta de hoy",
        "university.book_title": "Libro",
        "university.chapter": "Capítulo",
        "university.page": "Página",
        "university.test": "Prueba",
        "university.pass_threshold": "Umbral de aprobación: 51%",
        "university.next_chapter": "Siguiente capítulo",
        "footer.copyright": "© AWESchool Todos los derechos reservados",
        "footer.tagline": "Aprende, juega, crece",
        "share.summary": "Estadísticas",
        "share.completed_lessons": "Lecciones completadas",
        "share.streak": "Días consecutivos",
        "share.points": "Puntos",
        "share.achievements": "Logros",
        "share.total_lessons": "Total de lecciones",
        "share.study_time": "Tiempo de estudio",
        "share.creating": "Creando captura...",
        "share.copied": "¡Estadísticas copiadas!",
        "share.button": "Compartir estadísticas",
        "tts.working": "La voz funciona con Google TTS",
        "tts.engine": "Motor actual",
        "tts.test_voice": "Probar voz",
        "tts.select_voice": "Seleccionar voz",
        "tts.speed": "Velocidad",
        "tts.pitch": "Tono",
        "tts.volume": "Volumen",
        "tts.info": "El texto es leído por Google TTS (gratis)",
        "file.export_title": "Exportar / importar datos",
        "file.export_desc": "Descarga todos tus datos como archivo JSON firmado",
        "file.import_desc": "Restaura tus datos desde un archivo exportado",
        "file.protected": "Los archivos están firmados por AWESchool. Los falsificados serán rechazados.",
        "file.warning": "La importación reemplazará los datos actuales.",
        "file.exported": "Datos exportados (archivo firmado)",
        "file.imported": "¡Datos importados con éxito del archivo!",
        "file.invalid": "Formato de archivo inválido",
        "file.read_error": "No se pudo leer el archivo",
        "lang.changed": "Idioma cambiado",
        "lang.select": "Seleccionar idioma",
        "lang.search": "Buscar idioma...",
        "lang.no_results": "No se encontraron resultados",
    },
    "fr": {
        "app.title": "Monde du Savoir",
        "app.subtitle": "AWESchool - Jeu Éducatif",
        "welcome.title": "Bienvenue",
        "welcome.name_placeholder": "Entrez votre nom",
        "welcome.start": "Commencer l'apprentissage",
        "welcome.new_user": "Nouvelle inscription",
        "welcome.restore": "J'ai déjà un compte — Restaurer",
        "welcome.desc": "Plateforme éducative interactive : 200+ matières, 10 000+ leçons, lecture vocale, examens.",
        "welcome.restore_file": "Restaurer depuis un fichier JSON",
        "welcome.choose_avatar": "Choisissez votre personnage",
        "home.greeting": "Bienvenue",
        "home.subtitle": "Choisissez une matière, apprenez les leçons, passez les examens",
        "subjects.core": "Matières principales",
        "subjects.science": "Sciences",
        "subjects.language": "Sciences humaines",
        "subjects.computer": "Professions informatiques",
        "subjects.advanced": "Technologies avancées",
        "lesson.listen": "Écouter",
        "lesson.stop": "Arrêter",
        "lesson.next": "Suivant",
        "lesson.prev": "Précédent",
        "lesson.start_exam": "Commencer l'examen",
        "lesson.lessons": "leçons",
        "lesson.completed": "terminé",
        "lesson.hint": "Obtenir un indice",
        "lesson.explanation": "Explication",
        "exam.question": "Question",
        "exam.check": "Vérifier",
        "exam.exit": "Quitter",
        "exam.congrats": "Félicitations",
        "exam.retry": "Réessayer",
        "exam.passed": "Vous avez réussi l'examen",
        "exam.need_60": "Besoin de 60%+ pour la leçon suivante",
        "stats.lessons": "Leçons terminées",
        "stats.streak": "Jours consécutifs",
        "stats.points": "Points",
        "stats.title": "Mes statistiques",
        "stats.achievements": "Succès",
        "stats.study_time": "Étudié",
        "stats.favorites": "Favoris",
        "stats.bookmarks": "Marque-pages",
        "settings.title": "Paramètres",
        "settings.theme": "Thème",
        "settings.theme_light": "Clair",
        "settings.theme_dark": "Sombre",
        "settings.theme_auto": "Auto",
        "settings.font_size": "Taille de police",
        "settings.font_small": "Petit",
        "settings.font_medium": "Moyen",
        "settings.font_large": "Grand",
        "settings.daily_goal": "Objectif quotidien",
        "settings.language": "Langue",
        "settings.learning_mode": "Mode d'apprentissage par défaut",
        "settings.tip": "Le thème sombre est meilleur pour étudier le soir. Grande police pour la vue.",
        "mode.school": "Scolaire",
        "mode.university": "Universitaire",
        "mode.school_desc": "Leçons faciles, coloré et interactif",
        "mode.university_desc": "Livre détaillé, 100+ pages, avec tests",
        "guides.title": "Guides",
        "guides.how_to_use": "Comment utiliser le site",
        "guides.start": "Comment commencer",
        "guides.start_desc": "Premiers pas sur le site",
        "guides.modes": "Scolaire et Universitaire",
        "guides.modes_desc": "Deux modes d'apprentissage",
        "guides.listen": "Écouter les leçons",
        "guides.listen_desc": "Lecture vocale",
        "guides.share": "Partager les statistiques",
        "guides.share_desc": "Envoyez votre progression à vos amis",
        "guides.export": "Exporter / Importer",
        "guides.export_desc": "Sauvegarde des données par fichier",
        "guides.languages": "200+ langues",
        "guides.languages_desc": "Changer la langue du site",
        "guides.achievements": "Succès",
        "guides.achievements_desc": "Concourez avec d'autres participants",
        "guides.all_guides": "Tous les guides",
        "guides.main": "Accueil",
        "guides.live_demo": "Démo en direct",
        "guides.step": "Étape",
        "export": "EXPORTER",
        "import": "IMPORTER",
        "profile.title": "Mon profil",
        "profile.share": "Partager le profil",
        "search.placeholder": "Rechercher des leçons...",
        "filter.all": "Tous",
        "filter.completed": "Terminés",
        "filter.available": "Disponibles",
        "filter.locked": "Verrouillés",
        "filter.favorites": "Favoris",
        "daily_goal": "Objectif quotidien",
        "recently_viewed": "Vus récemment",
        "continue_learning": "Continuer l'apprentissage",
        "reset": "Recommencer",
        "share_data": "Partager les données",
        "back_to_subjects": "Matières",
        "my_achievements": "Mes succès",
        "confirm_reset": "Êtes-vous sûr de vouloir supprimer toute la progression ?",
        "daily_goal_done": "🎉 Félicitations ! L'objectif du jour est atteint !",
        "daily_goal_remaining": "{n} leçons restantes pour atteindre l'objectif du jour",
        "university.book_title": "Livre",
        "university.chapter": "Chapitre",
        "university.page": "Page",
        "university.test": "Test",
        "university.pass_threshold": "Seuil de réussite : 51%",
        "university.next_chapter": "Chapitre suivant",
        "footer.copyright": "© AWESchool Tous droits réservés",
        "footer.tagline": "Apprends, joue, grandis",
        "share.summary": "Statistiques",
        "share.completed_lessons": "Leçons terminées",
        "share.streak": "Jours consécutifs",
        "share.points": "Points",
        "share.achievements": "Succès",
        "share.total_lessons": "Total des leçons",
        "share.study_time": "Temps d'étude",
        "share.creating": "Création de la capture...",
        "share.copied": "Statistiques copiées !",
        "share.button": "Partager les statistiques",
        "tts.working": "La voix fonctionne via Google TTS",
        "tts.engine": "Moteur actuel",
        "tts.test_voice": "Tester la voix",
        "tts.select_voice": "Sélectionner la voix",
        "tts.speed": "Vitesse",
        "tts.pitch": "Tonalité",
        "tts.volume": "Volume",
        "tts.info": "Le texte est lu par Google TTS (gratuit)",
        "file.export_title": "Export / import de données",
        "file.export_desc": "Téléchargez toutes vos données dans un fichier JSON signé",
        "file.import_desc": "Restaurez vos données depuis un fichier précédemment exporté",
        "file.protected": "Les fichiers sont signés par AWESchool. Les fichiers falsifiés seront rejetés.",
        "file.warning": "L'importation remplacera les données actuelles.",
        "file.exported": "Données exportées (fichier signé)",
        "file.imported": "Données importées avec succès depuis le fichier !",
        "file.invalid": "Format de fichier invalide",
        "file.read_error": "Échec de lecture du fichier",
        "lang.changed": "Langue changée",
        "lang.select": "Sélectionner la langue",
        "lang.search": "Rechercher une langue...",
        "lang.no_results": "Aucun résultat trouvé",
    },
    "de": {
        "app.title": "Welt des Wissens",
        "app.subtitle": "AWESchool - Lernspiel",
        "welcome.title": "Willkommen",
        "welcome.name_placeholder": "Gib deinen Namen ein",
        "welcome.start": "Lernen beginnen",
        "welcome.new_user": "Neue Registrierung",
        "welcome.restore": "Ich habe schon ein Konto — Wiederherstellen",
        "welcome.desc": "Interaktive Lernplattform: 200+ Fächer, 10.000+ Lektionen, Sprachausgabe, Prüfungen.",
        "welcome.restore_file": "Aus JSON-Datei wiederherstellen",
        "welcome.choose_avatar": "Wähle deinen Charakter",
        "home.greeting": "Willkommen",
        "home.subtitle": "Wähle ein Fach, lerne Lektionen, bestehe Prüfungen",
        "subjects.core": "Hauptfächer",
        "subjects.science": "Naturwissenschaften",
        "subjects.language": "Geisteswissenschaften",
        "subjects.computer": "Computerberufe",
        "subjects.advanced": "Fortgeschrittene Technologien",
        "lesson.listen": "Anhören",
        "lesson.stop": "Stopp",
        "lesson.next": "Weiter",
        "lesson.prev": "Zurück",
        "lesson.start_exam": "Prüfung beginnen",
        "lesson.lessons": "Lektionen",
        "lesson.completed": "abgeschlossen",
        "lesson.hint": "Tipp erhalten",
        "lesson.explanation": "Erklärung",
        "exam.question": "Frage",
        "exam.check": "Prüfen",
        "exam.exit": "Beenden",
        "exam.congrats": "Glückwunsch",
        "exam.retry": "Nochmal versuchen",
        "exam.passed": "Du hast die Prüfung bestanden",
        "exam.need_60": "60%+ für die nächste Lektion nötig",
        "stats.lessons": "Abgeschlossene Lektionen",
        "stats.streak": "Tage in Folge",
        "stats.points": "Punkte",
        "stats.title": "Meine Statistiken",
        "stats.achievements": "Erfolge",
        "stats.study_time": "Gelernt",
        "stats.favorites": "Favoriten",
        "stats.bookmarks": "Lesezeichen",
        "settings.title": "Einstellungen",
        "settings.theme": "Design",
        "settings.theme_light": "Hell",
        "settings.theme_dark": "Dunkel",
        "settings.theme_auto": "Auto",
        "settings.font_size": "Schriftgröße",
        "settings.font_small": "Klein",
        "settings.font_medium": "Mittel",
        "settings.font_large": "Groß",
        "settings.daily_goal": "Tagesziel",
        "settings.language": "Sprache",
        "settings.learning_mode": "Standard-Lernmodus",
        "settings.tip": "Dunkles Design ist besser für Abendstudium. Große Schrift für die Sicht.",
        "mode.school": "Schule",
        "mode.university": "Universität",
        "mode.school_desc": "Einfache Lektionen, bunt und interaktiv",
        "mode.university_desc": "Detailliertes Buch, 100+ Seiten, mit Tests",
        "guides.title": "Anleitungen",
        "guides.how_to_use": "So benutzt du die Seite",
        "guides.start": "Wie man anfängt",
        "guides.start_desc": "Erste Schritte auf der Seite",
        "guides.modes": "Schule und Universität",
        "guides.modes_desc": "Zwei Lernmodi",
        "guides.listen": "Lektionen anhören",
        "guides.listen_desc": "Sprachausgabe",
        "guides.share": "Statistiken teilen",
        "guides.share_desc": "Sende deinen Fortschritt an Freunde",
        "guides.export": "Export / Import",
        "guides.export_desc": "Dateibasierte Datensicherung",
        "guides.languages": "200+ Sprachen",
        "guides.languages_desc": "Seitensprache ändern",
        "guides.achievements": "Erfolge",
        "guides.achievements_desc": "Wetteifere mit anderen Teilnehmern",
        "guides.all_guides": "Alle Anleitungen",
        "guides.main": "Start",
        "guides.live_demo": "Live-Demo",
        "guides.step": "Schritt",
        "export": "EXPORT",
        "import": "IMPORT",
        "profile.title": "Mein Profil",
        "profile.share": "Profil teilen",
        "search.placeholder": "Lektionen suchen...",
        "filter.all": "Alle",
        "filter.completed": "Abgeschlossen",
        "filter.available": "Verfügbar",
        "filter.locked": "Gesperrt",
        "filter.favorites": "Favoriten",
        "daily_goal": "Tagesziel",
        "recently_viewed": "Zuletzt angesehen",
        "continue_learning": "Weiterlernen",
        "reset": "Neu starten",
        "share_data": "Daten teilen",
        "back_to_subjects": "Fächer",
        "my_achievements": "Meine Erfolge",
        "confirm_reset": "Bist du sicher, dass du den gesamten Fortschritt löschen willst?",
        "daily_goal_done": "🎉 Glückwunsch! Tagesziel erreicht!",
        "daily_goal_remaining": "Noch {n} Lektionen bis zum Tagesziel",
        "university.book_title": "Buch",
        "university.chapter": "Kapitel",
        "university.page": "Seite",
        "university.test": "Test",
        "university.pass_threshold": "Bestehensgrenze: 51%",
        "university.next_chapter": "Nächstes Kapitel",
        "footer.copyright": "© AWESchool Alle Rechte vorbehalten",
        "footer.tagline": "Lerne, spiele, wachse",
        "share.summary": "Statistiken",
        "share.completed_lessons": "Abgeschlossene Lektionen",
        "share.streak": "Tage in Folge",
        "share.points": "Punkte",
        "share.achievements": "Erfolge",
        "share.total_lessons": "Gesamte Lektionen",
        "share.study_time": "Lernzeit",
        "share.creating": "Screenshot wird erstellt...",
        "share.copied": "Statistiken kopiert!",
        "share.button": "Statistiken teilen",
        "tts.working": "Stimme funktioniert über Google TTS",
        "tts.engine": "Aktuelle Engine",
        "tts.test_voice": "Stimme testen",
        "tts.select_voice": "Stimme wählen",
        "tts.speed": "Geschwindigkeit",
        "tts.pitch": "Tonhöhe",
        "tts.volume": "Lautstärke",
        "tts.info": "Text wird von Google TTS gelesen (kostenlos)",
        "file.export_title": "Daten Export / Import",
        "file.export_desc": "Lade alle deine Daten als signierte JSON-Datei herunter",
        "file.import_desc": "Stelle deine Daten aus einer zuvor exportierten Datei wieder her",
        "file.protected": "Dateien sind von AWESchool signiert. Gefälschte Dateien werden abgelehnt.",
        "file.warning": "Der Import ersetzt aktuelle Daten.",
        "file.exported": "Daten exportiert (signierte Datei)",
        "file.imported": "Daten erfolgreich aus Datei importiert!",
        "file.invalid": "Ungültiges Dateiformat",
        "file.read_error": "Datei konnte nicht gelesen werden",
        "lang.changed": "Sprache geändert",
        "lang.select": "Sprache wählen",
        "lang.search": "Sprache suchen...",
        "lang.no_results": "Keine Ergebnisse gefunden",
    },
}

# ---------------------------------------------------------------------------
# Generate the .ts files
# ---------------------------------------------------------------------------

def quote(s: str) -> str:
    """Quote a string for TypeScript. Escape single quotes & backslashes."""
    s = s.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"

def write_full_file(code: str, translations: dict):
    """Write a complete translation file with all keys."""
    lines = []
    lines.append(f"// {code} - UI translations")
    lines.append(f"// Auto-generated. Full hand-curated translation.")
    lines.append("")
    lines.append(f"export const {code}: Record<string, string> = {{")
    for k, v in translations.items():
        lines.append(f"  {quote(k)}: {quote(v)},")
    lines.append("}")
    lines.append("")
    (OUT_DIR / f"{code}.ts").write_text("\n".join(lines), encoding="utf-8")

# Write hand-curated files
for code, translations in TRANSLATIONS.items():
    write_full_file(code, translations)
    print(f"  ✓ {code}.ts ({len(translations)} keys)")

print(f"\n✓ Generated {len(TRANSLATIONS)} full translation files")
