#!/usr/bin/env python3
"""
Generate remaining hand-curated translation files.
For these languages we provide a minimal but correct translation of all 137 keys.
"""

from pathlib import Path

OUT_DIR = Path("/home/z/my-project/src/lib/i18n/translations")
OUT_DIR.mkdir(parents=True, exist_ok=True)

KEYS = [
    "app.title","app.subtitle","welcome.title","welcome.name_placeholder","welcome.start",
    "welcome.new_user","welcome.restore","welcome.desc","welcome.restore_file","welcome.choose_avatar",
    "home.greeting","home.subtitle","subjects.core","subjects.science","subjects.language",
    "subjects.computer","subjects.advanced","lesson.listen","lesson.stop","lesson.next",
    "lesson.prev","lesson.start_exam","lesson.lessons","lesson.completed","lesson.hint",
    "lesson.explanation","exam.question","exam.check","exam.exit","exam.congrats",
    "exam.retry","exam.passed","exam.need_60","stats.lessons","stats.streak",
    "stats.points","stats.title","stats.achievements","stats.study_time","stats.favorites",
    "stats.bookmarks","settings.title","settings.theme","settings.theme_light","settings.theme_dark",
    "settings.theme_auto","settings.font_size","settings.font_small","settings.font_medium","settings.font_large",
    "settings.daily_goal","settings.language","settings.learning_mode","settings.tip","mode.school",
    "mode.university","mode.school_desc","mode.university_desc","guides.title","guides.how_to_use",
    "guides.start","guides.start_desc","guides.modes","guides.modes_desc","guides.listen",
    "guides.listen_desc","guides.share","guides.share_desc","guides.export","guides.export_desc",
    "guides.languages","guides.languages_desc","guides.achievements","guides.achievements_desc","guides.all_guides",
    "guides.main","guides.live_demo","guides.step","export","import",
    "profile.title","profile.share","search.placeholder","filter.all","filter.completed",
    "filter.available","filter.locked","filter.favorites","daily_goal","recently_viewed",
    "continue_learning","reset","share_data","back_to_subjects","my_achievements",
    "confirm_reset","daily_goal_done","daily_goal_remaining","university.book_title","university.chapter",
    "university.page","university.test","university.pass_threshold","university.next_chapter","footer.copyright",
    "footer.tagline","share.summary","share.completed_lessons","share.streak","share.points",
    "share.achievements","share.total_lessons","share.study_time","share.creating","share.copied",
    "share.button","tts.working","tts.engine","tts.test_voice","tts.select_voice",
    "tts.speed","tts.pitch","tts.volume","tts.info","file.export_title",
    "file.export_desc","file.import_desc","file.protected","file.warning","file.exported",
    "file.imported","file.invalid","file.read_error","lang.changed","lang.select",
    "lang.search","lang.no_results",
]
assert len(KEYS) == 137

TRANSLATIONS = {}

# Indonesian
TRANSLATIONS["id"] = [
    "Dunia Pengetahuan","AWESchool - Game Edukatif","Selamat datang","Masukkan nama Anda","Mulai belajar",
    "Pendaftaran baru","Saya sudah punya akun — Pulihkan","Platform edukasi interaktif: 200+ mata pelajaran, 10.000+ pelajaran, baca suara, ujian.","Pulihkan dari file JSON","Pilih karakter Anda",
    "Selamat datang","Pilih mata pelajaran, pelajari pelajaran, lulus ujian","Mata pelajaran inti","Sains","Humaniora",
    "Profesi komputer","Teknologi canggih","Dengarkan","Berhenti","Berikutnya",
    "Sebelumnya","Mulai ujian","pelajaran","selesai","Dapatkan petunjuk",
    "Penjelasan","Pertanyaan","Periksa","Keluar","Selamat",
    "Coba lagi","Anda berhasil lulus ujian","Butuh 60%+ untuk pelajaran berikutnya","Pelajaran selesai","Hari berturut-turut",
    "Poin","Statistik saya","Pencapaian","Dipelajari","Favorit",
    "Markah","Pengaturan","Tema","Terang","Gelap",
    "Otomatis","Ukuran font","Kecil","Sedang","Besar",
    "Tujuan harian","Bahasa","Mode belajar default","Tema gelap lebih baik untuk belajar malam. Font besar untuk penglihatan.","Sekolah",
    "Universitas","Pelajaran mudah, berwarna dan interaktif","Buku terperinci, 100+ halaman, dengan tes","Panduan","Cara menggunakan situs",
    "Cara memulai","Langkah pertama di situs","Sekolah dan Universitas","Dua mode belajar","Dengarkan pelajaran",
    "Baca suara","Bagikan statistik","Kirim kemajuan Anda ke teman","Ekspor / Impor","Cadangan data berbasis file",
    "200+ bahasa","Ubah bahasa situs","Pencapaian","Bersaing dengan peserta lain","Semua panduan",
    "Beranda","Demo langsung","Langkah","EKSPOR","IMPOR",
    "Profil saya","Bagikan profil","Cari pelajaran...","Semua","Selesai",
    "Tersedia","Terkunci","Favorit","Tujuan harian","Baru dilihat",
    "Lanjutkan belajar","Mulai ulang","Bagikan data","Mata pelajaran","Pencapaian saya",
    "Apakah Anda yakin ingin menghapus semua kemajuan?","🎉 Selamat! Tujuan hari ini tercapai!","Sisa {n} pelajaran untuk tujuan hari ini","Buku","Bab",
    "Halaman","Tes","Ambang batas: 51%","Bab berikutnya","© AWESchool Hak cipta dilindungi",
    "Belajar, bermain, tumbuh","Statistik","Pelajaran selesai","Hari berturut-turut","Poin",
    "Pencapaian","Total pelajaran","Waktu belajar","Membuat tangkapan layar...","Statistik disalin!",
    "Bagikan statistik","Suara berfungsi via Google TTS","Mesin saat ini","Uji suara","Pilih suara",
    "Kecepatan","Nada","Volume","Teks dibaca oleh Google TTS (gratis)","Ekspor / impor data",
    "Unduh semua data Anda sebagai file JSON bertanda tangan","Pulihkan data Anda dari file yang diekspor sebelumnya","File ditandatangani oleh AWESchool. File palsu akan ditolak.","Impor akan menggantikan data saat ini.","Data diekspor (file bertanda tangan)",
    "Data berhasil diimpor dari file!","Format file tidak valid","Gagal membaca file","Bahasa diubah","Pilih bahasa",
    "Cari bahasa...","Tidak ada hasil ditemukan",
]

# Vietnamese
TRANSLATIONS["vi"] = [
    "Thế Giới Tri Thức","AWESchool - Trò Chơi Giáo Dục","Chào mừng","Nhập tên của bạn","Bắt đầu học",
    "Đăng ký mới","Tôi đã có tài khoản — Khôi phục","Nền tảng giáo dục tương tác: 200+ môn học, 10.000+ bài học, đọc bằng giọng nói, kỳ thi.","Khôi phục từ tệp JSON","Chọn nhân vật của bạn",
    "Chào mừng","Chọn một môn học, học bài học, vượt qua kỳ thi","Môn học chính","Khoa học","Khoa học nhân văn",
    "Nghề máy tính","Công nghệ tiên tiến","Nghe","Dừng","Tiếp theo",
    "Trước đó","Bắt đầu kỳ thi","bài học","đã hoàn thành","Nhận gợi ý",
    "Giải thích","Câu hỏi","Kiểm tra","Thoát","Chúc mừng",
    "Thử lại","Bạn đã vượt qua kỳ thi","Cần 60%+ cho bài học tiếp theo","Bài học đã hoàn thành","Ngày liên tiếp",
    "Điểm","Thống kê của tôi","Thành tích","Đã học","Yêu thích",
    "Dấu trang","Cài đặt","Chủ đề","Sáng","Tối",
    "Tự động","Cỡ chữ","Nhỏ","Trung bình","Lớn",
    "Mục tiêu hàng ngày","Ngôn ngữ","Chế độ học mặc định","Chủ đề tối tốt hơn cho việc học buổi tối. Chữ lớn cho thị lực.","Trường học",
    "Đại học","Bài học dễ, nhiều màu và tương tác","Sách chi tiết, 100+ trang, với bài kiểm tra","Hướng dẫn","Cách sử dụng trang web",
    "Cách bắt đầu","Bước đầu tiên trên trang web","Trường học và Đại học","Hai chế độ học","Nghe bài học",
    "Đọc bằng giọng nói","Chia sẻ thống kê","Gửi tiến độ của bạn cho bạn bè","Xuất / Nhập","Sao lưu dữ liệu dựa trên tệp",
    "200+ ngôn ngữ","Thay đổi ngôn ngữ trang web","Thành tích","Cạnh tranh với người tham gia khác","Tất cả hướng dẫn",
    "Trang chủ","Demo trực tiếp","Bước","XUẤT","NHẬP",
    "Hồ sơ của tôi","Chia sẻ hồ sơ","Tìm bài học...","Tất cả","Đã hoàn thành",
    "Khả dụng","Đã khóa","Yêu thích","Mục tiêu hàng ngày","Xem gần đây",
    "Tiếp tục học","Bắt đầu lại","Chia sẻ dữ liệu","Môn học","Thành tích của tôi",
    "Bạn có chắc muốn xóa tất cả tiến độ?","🎉 Chúc mừng! Đã đạt mục tiêu hôm nay!","Còn {n} bài học để đạt mục tiêu hôm nay","Sách","Chương",
    "Trang","Kiểm tra","Ngưỡng đậu: 51%","Chương tiếp theo","© AWESchool Mọi quyền được bảo lưu",
    "Học, chơi, phát triển","Thống kê","Bài học đã hoàn thành","Ngày liên tiếp","Điểm",
    "Thành tích","Tổng bài học","Thời gian học","Đang tạo ảnh chụp màn hình...","Đã sao chép thống kê!",
    "Chia sẻ thống kê","Giọng nói hoạt động qua Google TTS","Công cụ hiện tại","Kiểm tra giọng nói","Chọn giọng nói",
    "Tốc độ","Cao độ","Âm lượng","Văn bản được đọc bởi Google TTS (miễn phí)","Xuất / nhập dữ liệu",
    "Tải xuống tất cả dữ liệu của bạn dưới dạng tệp JSON đã ký","Khôi phục dữ liệu của bạn từ tệp đã xuất trước đó","Các tệp được ký bởi AWESchool. Tệp giả sẽ bị từ chối.","Nhập sẽ thay thế dữ liệu hiện tại.","Đã xuất dữ liệu (tệp đã ký)",
    "Đã nhập dữ liệu thành công từ tệp!","Định dạng tệp không hợp lệ","Không thể đọc tệp","Đã thay đổi ngôn ngữ","Chọn ngôn ngữ",
    "Tìm ngôn ngữ...","Không tìm thấy kết quả",
]

# Thai
TRANSLATIONS["th"] = [
    "โลกแห่งความรู้","AWESchool - เกมการศึกษา","ยินดีต้อนรับ","ป้อนชื่อของคุณ","เริ่มเรียน",
    "ลงทะเบียนใหม่","ฉันมีบัญชีอยู่แล้ว — กู้คืน","แพลตฟอร์มการศึกษาเชิงโต้ตอบ: 200+ วิชา, 10,000+ บทเรียน, อ่านด้วยเสียง, การสอบ.","กู้คืนจากไฟล์ JSON","เลือกตัวละครของคุณ",
    "ยินดีต้อนรับ","เลือกวิชา, เรียนบทเรียน, สอบให้ผ่าน","วิชาหลัก","วิทยาศาสตร์","มนุษยศาสตร์",
    "อาชีพคอมพิวเตอร์","เทคโนโลยีขั้นสูง","ฟัง","หยุด","ถัดไป",
    "ก่อนหน้า","เริ่มสอบ","บทเรียน","เสร็จสิ้น","รับคำใบ้",
    "คำอธิบาย","คำถาม","ตรวจสอบ","ออก","ยินดีด้วย",
    "ลองอีกครั้ง","คุณสอบผ่านแล้ว","ต้องการ 60%+ สำหรับบทเรียนถัดไป","บทเรียนที่เสร็จสิ้น","วันต่อเนื่อง",
    "คะแนน","สถิติของฉัน","ความสำเร็จ","ได้เรียนแล้ว","รายการโปรด",
    "ที่คั่นหน้า","การตั้งค่า","ธีม","สว่าง","มืด",
    "อัตโนมัติ","ขนาดตัวอักษร","เล็ก","กลาง","ใหญ่",
    "เป้าหมายประจำวัน","ภาษา","โหมดการเรียนเริ่มต้น","ธีมมืดดีกว่าสำหรับการเรียนตอนเย็น ตัวอักษรใหญ่สำหรับสายตา","โรงเรียน",
    "มหาวิทยาลัย","บทเรียนง่าย สีสันสดใส และโต้ตอบได้","หนังสือโดยละเอียด 100+ หน้า พร้อมแบบทดสอบ","คู่มือ","วิธีใช้เว็บไซต์",
    "วิธีเริ่มต้น","ก้าวแรกบนเว็บไซต์","โรงเรียนและมหาวิทยาลัย","สองโหมดการเรียน","ฟังบทเรียน",
    "อ่านด้วยเสียง","แชร์สถิติ","ส่งความคืบหน้าของคุณให้เพื่อน","ส่งออก / นำเข้า","สำรองข้อมูลบนไฟล์",
    "200+ ภาษา","เปลี่ยนภาษาของเว็บไซต์","ความสำเร็จ","แข่งขันกับผู้เข้าร่วมคนอื่น","คู่มือทั้งหมด",
    "หน้าหลัก","สาธิตสด","ขั้นตอน","ส่งออก","นำเข้า",
    "โปรไฟล์ของฉัน","แชร์โปรไฟล์","ค้นหาบทเรียน...","ทั้งหมด","เสร็จสิ้น",
    "พร้อมใช้งาน","ล็อค","รายการโปรด","เป้าหมายประจำวัน","ดูล่าสุด",
    "เรียนต่อ","เริ่มใหม่","แชร์ข้อมูล","วิชา","ความสำเร็จของฉัน",
    "คุณแน่ใจหรือว่าต้องการลบความคืบหน้าทั้งหมด?","🎉 ยินดีด้วย! บรรลุเป้าหมายวันนี้แล้ว!","เหลืออีก {n} บทเรียนถึงเป้าหมายวันนี้","หนังสือ","บท",
    "หน้า","แบบทดสอบ","เกณฑ์ผ่าน: 51%","บทถัดไป","© AWESchool สงวนลิขสิทธิ์ทั้งหมด",
    "เรียน เล่น เติบโต","สถิติ","บทเรียนที่เสร็จสิ้น","วันต่อเนื่อง","คะแนน",
    "ความสำเร็จ","บทเรียนทั้งหมด","เวลาเรียน","กำลังสร้างภาพหน้าจอ...","คัดลอกสถิติแล้ว!",
    "แชร์สถิติ","เสียงทำงานผ่าน Google TTS","เอนจินปัจจุบัน","ทดสอบเสียง","เลือกเสียง",
    "ความเร็ว","ระดับเสียง","ระดับเสียง","ข้อความถูกอ่านโดย Google TTS (ฟรี)","ส่งออก / นำเข้าข้อมูล",
    "ดาวน์โหลดข้อมูลทั้งหมดของคุณเป็นไฟล์ JSON ที่ลงนาม","กู้คืนข้อมูลของคุณจากไฟล์ที่ส่งออกก่อนหน้า","ไฟล์ถูกลงนามโดย AWESchool ไฟล์ปลอมจะถูกปฏิเสธ","การนำเข้าจะแทนที่ข้อมูลปัจจุบัน","ส่งออกข้อมูลแล้ว (ไฟล์ที่ลงนาม)",
    "นำเข้าข้อมูลจากไฟล์สำเร็จ!","รูปแบบไฟล์ไม่ถูกต้อง","ไม่สามารถอ่านไฟล์ได้","เปลี่ยนภาษาแล้ว","เลือกภาษา",
    "ค้นหาภาษา...","ไม่พบผลลัพธ์",
]

# Swedish
TRANSLATIONS["sv"] = [
    "Kunskapens Värld","AWESchool - Utbildningsspel","Välkommen","Ange ditt namn","Börja lära",
    "Ny registrering","Jag har redan ett konto — Återställ","Interaktiv utbildningsplattform: 200+ ämnen, 10 000+ lektioner, röstläsning, tentamina.","Återställ från JSON-fil","Välj din karaktär",
    "Välkommen","Välj ett ämne, lär lektioner, klara tentamina","Huvudämnen","Vetenskaper","Humaniora",
    "Datayrken","Avancerad teknik","Lyssna","Stopp","Nästa",
    "Föregående","Starta tentamen","lektioner","slutförda","Få tips",
    "Förklaring","Fråga","Kontrollera","Avsluta","Gratulerar",
    "Försök igen","Du klarade tentamen","Behöver 60%+ för nästa lektion","Slutförda lektioner","Dagar i rad",
    "Poäng","Min statistik","Prestationer","Studerat","Favoriter",
    "Bokmärken","Inställningar","Tema","Ljust","Mörkt",
    "Auto","Teckenstorlek","Liten","Medel","Stor",
    "Dagligt mål","Språk","Standardinlärningsläge","Mörkt tema är bättre för kvällsstudier. Stort teckensnitt för synen.","Skola",
    "Universitet","Enkla lektioner, färgglatt och interaktivt","Detaljerad bok, 100+ sidor, med tester","Guider","Hur man använder sajten",
    "Hur man börjar","Första stegen på sajten","Skola och Universitet","Två inlärningslägen","Lyssna på lektioner",
    "Röstläsning","Dela statistik","Skicka din framgång till vänner","Exportera / Importera","Filbaserad säkerhetskopiering",
    "200+ språk","Ändra sajtspråk","Prestationer","Tävla med andra deltagare","Alla guider",
    "Hem","Live-demo","Steg","EXPORTERA","IMPORTERA",
    "Min profil","Dela profil","Sök lektioner...","Alla","Slutförda",
    "Tillgängliga","Låsta","Favoriter","Dagligt mål","Nyligen visade",
    "Fortsätt lära","Börja om","Dela data","Ämnen","Mina prestationer",
    "Är du säker på att du vill radera all framgång?","🎉 Gratulerar! Dagens mål uppnått!","{n} lektioner kvar till dagens mål","Bok","Kapitel",
    "Sida","Test","Godkändgräns: 51%","Nästa kapitel","© AWESchool Alla rättigheter förbehållna",
    "Lär, lek, väx","Statistik","Slutförda lektioner","Dagar i rad","Poäng",
    "Prestationer","Totalt lektioner","Studietid","Skapar skärmdump...","Statistik kopierad!",
    "Dela statistik","Röst fungerar via Google TTS","Aktuell motor","Testa röst","Välj röst",
    "Hastighet","Tonhöjd","Volym","Text läses av Google TTS (gratis)","Dataexport / import",
    "Ladda ner alla dina data som en signerad JSON-fil","Återställ dina data från en tidigare exporterad fil","Filer signeras av AWESchool. Falska filer kommer att avvisas.","Import kommer att ersätta aktuella data.","Data exporterad (signerad fil)",
    "Data framgångsrikt importerad från fil!","Ogiltigt filformat","Kunde inte läsa fil","Språk ändrat","Välj språk",
    "Sök språk...","Inga resultat hittades",
]

# Norwegian
TRANSLATIONS["no"] = [
    "Kunnskapens Verden","AWESchool - Lærespill","Velkommen","Skriv inn navnet ditt","Begynn å lære",
    "Ny registrering","Jeg har allerede en konto — Gjenopprett","Interaktiv læringsplattform: 200+ fag, 10 000+ leksjoner, stemmelesing, eksamener.","Gjenopprett fra JSON-fil","Velg karakteren din",
    "Velkommen","Velg et fag, lær leksjoner, bestå eksamener","Hovedfag","Vitenskaper","Humaniora",
    "Datayrker","Avansert teknologi","Lytt","Stopp","Neste",
    "Forrige","Start eksamen","leksjoner","fullført","Få hint",
    "Forklaring","Spørsmål","Sjekk","Avslutt","Gratulerer",
    "Prøv igjen","Du besto eksamen","Trenger 60%+ for neste leksjon","Fullførte leksjoner","Dager på rad",
    "Poeng","Min statistikk","Prestasjoner","Studert","Favoritter",
    "Bokmerker","Innstillinger","Tema","Lyst","Mørkt",
    "Auto","Skriftstørrelse","Liten","Middels","Stor",
    "Daglig mål","Språk","Standard læringsmodus","Mørkt tema er bedre for kveldsstudier. Stor skrift for synet.","Skole",
    "Universitet","Enkle leksjoner, fargerik og interaktiv","Detaljert bok, 100+ sider, med tester","Veiledninger","Hvordan bruke nettstedet",
    "Hvordan begynne","Første skritt på nettstedet","Skole og Universitet","To læringsmoduser","Lytt til leksjoner",
    "Stemmelesing","Del statistikk","Send fremgangen din til venner","Eksporter / Importer","Filbasert sikkerhetskopiering",
    "200+ språk","Endre nettstedets språk","Prestasjoner","Konkurrer med andre deltakere","Alle veiledninger",
    "Hjem","Live-demo","Trinn","EKSPORTER","IMPORTER",
    "Min profil","Del profil","Søk leksjoner...","Alle","Fullført",
    "Tilgjengelig","Låst","Favoritter","Daglig mål","Nylig sett",
    "Fortsett å lære","Begynn på nytt","Del data","Fag","Mine prestasjoner",
    "Er du sikker på at du vil slette all fremgang?","🎉 Gratulerer! Dagens mål oppnådd!","{n} leksjoner igjen til dagens mål","Bok","Kapittel",
    "Side","Test","Beståttsgrense: 51%","Neste kapittel","© AWESchool Alle rettigheter forbeholdt",
    "Lær, lek, vokse","Statistikk","Fullførte leksjoner","Dager på rad","Poeng",
    "Prestasjoner","Totalt leksjoner","Studietid","Lager skjermbilde...","Statistikk kopiert!",
    "Del statistikk","Stemmen fungerer via Google TTS","Nåværende motor","Test stemme","Velg stemme",
    "Hastighet","Tonehøyde","Volum","Tekst leses av Google TTS (gratis","Dataeksport / import",
    "Last ned alle dataene dine som en signert JSON-fil","Gjenopprett dataene dine fra en tidligere eksportert fil","Filer signeres av AWESchool. Forfalskede filer vil bli avvist.","Import vil erstatte nåværende data.","Data eksportert (signert fil)",
    "Data vellykket importert fra fil!","Ugyldig filformat","Kunne ikke lese fil","Språk endret","Velg språk",
    "Søk språk...","Ingen resultater funnet",
]

# Danish
TRANSLATIONS["da"] = [
    "Videnens Verden","AWESchool - Læringspil","Velkommen","Indtast dit navn","Begynd at lære",
    "Ny registrering","Jeg har allerede en konto — Gendan","Interaktiv læringsplatform: 200+ fag, 10.000+ lektioner, stemmeoplæsning, eksamener.","Gendan fra JSON-fil","Vælg din karakter",
    "Velkommen","Vælg et fag, lær lektioner, bestå eksamener","Hovedfag","Videnskaber","Humaniora",
    "Computerfag","Avanceret teknologi","Lyt","Stop","Næste",
    "Forrige","Start eksamen","lektioner","fuldført","Få tip",
    "Forklaring","Spørgsmål","Tjek","Afslut","Tillykke",
    "Prøv igen","Du bestod eksamen","Brug for 60%+ til næste lektion","Fuldførte lektioner","Dage i træk",
    "Point","Min statistik","Præstationer","Studeret","Favoritter",
    "Bogmærker","Indstillinger","Tema","Lyst","Mørkt",
    "Auto","Skriftstørrelse","Lille","Mellem","Stor",
    "Dagligt mål","Sprog","Standard læringstilstand","Mørkt tema er bedre til aftensstudier. Stor skrift til synet.","Skole",
    "Universitet","Nemme lektioner, farverig og interaktiv","Detaljeret bog, 100+ sider, med tests","Vejledninger","Sådan bruger du webstedet",
    "Sådan starter du","Første skridt på webstedet","Skole og Universitet","To læringsmåder","Lyt til lektioner",
    "Stemmeoplæsning","Del statistik","Send dit fremskridt til venner","Eksporter / Importer","Filbaseret sikkerhedskopiering",
    "200+ sprog","Skift webstedets sprog","Præstationer","Konkurrer med andre deltagere","Alle vejledninger",
    "Hjem","Live-demo","Trin","EKSPORTER","IMPORTER",
    "Min profil","Del profil","Søg lektioner...","Alle","Fuldført",
    "Tilgængelig","Låst","Favoritter","Dagligt mål","Set for nylig",
    "Fortsæt med at lære","Begynd forfra","Del data","Fag","Mine præstationer",
    "Er du sikker på, at du vil slette alt fremskridt?","🎉 Tillykke! Dagens mål er nået!","{n} lektioner tilbage til dagens mål","Bog","Kapitel",
    "Side","Test","Beståelsesgrænse: 51%","Næste kapitel","© AWESchool Alle rettigheder forbeholdes",
    "Lær, leg, voks","Statistik","Fuldførte lektioner","Dage i træk","Point",
    "Præstationer","Total lektioner","Studietid","Opretter skærmbillede...","Statistik kopieret!",
    "Del statistik","Stemme fungerer via Google TTS","Nuværende motor","Test stemme","Vælg stemme",
    "Hastighed","Tonehøjde","Lydstyrke","Tekst læses af Google TTS (gratis","Dataeksport / import",
    "Download alle dine data som en underskrevet JSON-fil","Gendan dine data fra en tidligere eksporteret fil","Filer underskrives af AWESchool. Forfalskede filer vil blive afvist.","Import vil erstatte nuværende data.","Data eksporteret (underskrevet fil)",
    "Data importeret med succes fra fil!","Ugyldigt filformat","Kunne ikke læse fil","Sprog ændret","Vælg sprog",
    "Søg sprog...","Ingen resultater fundet",
]

# Finnish
TRANSLATIONS["fi"] = [
    "Tiedon Maailma","AWESchool - Oppimispeli","Tervetuloa","Syötä nimesi","Aloita oppiminen",
    "Uusi rekisteröityminen","Minulla on jo tili — Palauta","Interaktiivinen oppimisalusta: 200+ aihetta, 10 000+ oppituntia, ääniluku, kokeet.","Palauta JSON-tiedostosta","Valitse hahmosi",
    "Tervetuloa","Valitse aihe, opi oppitunteja, suorita kokeet","Pääaineet","Tieteet","Humanistiset tieteet",
    "Tietokoneammatit","Kehittynyt teknologia","Kuuntele","Pysäytä","Seuraava",
    "Edellinen","Aloita koe","oppituntia","suoritettu","Saa vihje",
    "Selitys","Kysymys","Tarkista","Poistu","Onnittelut",
    "Yritä uudelleen","Läpäisit kokeen","Tarvitaan 60%+ seuraavaan oppituntiin","Suoritetut oppitunnit","Peräkkäiset päivät",
    "Pisteet","Tilastoni","Saavutukset","Opittu","Suosikit",
    "Kirjanmerkit","Asetukset","Teema","Vaalea","Tumma",
    "Auto","Fonttikoko","Pieni","Keskisuuri","Suuri",
    "Päivittäinen tavoite","Kieli","Oletusoppimistila","Tumma teema on parempi iltaopiskeluun. Suuri fontti näölle.","Koulu",
    "Yliopisto","Helpot oppitunnit, värikäs ja interaktiivinen","Yksityiskohtainen kirja, 100+ sivua, kokeilla","Oppaat","Kuinka käyttää sivustoa",
    "Miten aloittaa","Ensimmäiset askeleet sivustolla","Koulu ja Yliopisto","Kaksi oppimistilaa","Kuuntele oppitunteja",
    "Ääniluku","Jaa tilastoja","Lähetä edistymisesi ystäville","Vie / Tuo","Tiedostopohjainen varmuuskopiointi",
    "200+ kieltä","Vaihda sivuston kieli","Saavutukset","Kilpaile muiden osallistujien kanssa","Kaikki oppaat",
    "Etusivu","Live-demo","Vaihe","VIE","TUO",
    "Profiilini","Jaa profiili","Etsi oppitunteja...","Kaikki","Suoritettu",
    "Saatavilla","Lukittu","Suosikit","Päivittäinen tavoite","Äskettäin katsotut",
    "Jatka oppimista","Aloita alusta","Jaa tiedot","Aineet","Saavutukseni",
    "Oletko varma, että haluat poistaa kaiken edistymisen?","🎉 Onnittelut! Päivän tavoite saavutettu!","{n} oppituntia jäljellä päivän tavoitteeseen","Kirja","Luku",
    "Sivu","Testi","Läpipääsyn raja: 51%","Seuraava luku","© AWESchool Kaikki oikeudet pidätetään",
    "Opi, leiki, kasva","Tilastot","Suoritetut oppitunnit","Peräkkäiset päivät","Pisteet",
    "Saavutukset","Oppitunnit yhteensä","Opiskeluaika","Luodaan kuvakaappausta...","Tilastot kopioitu!",
    "Jaa tilastot","Ääni toimii Google TTS:n kautta","Nykyinen moottori","Testaa ääni","Valitse ääni",
    "Nopeus","Sävelkorkeus","Äänenvoimakkuus","Tekstin lukee Google TTS (ilmainen","Tietojen vienti / tuonti",
    "Lataa kaikki tietosi allekirjoitettuna JSON-tiedostona","Palauta tietosi aiemmin viedystä tiedostosta","Tiedostot allekirjoittaa AWESchool. Väärennetyt tiedostot hylätään.","Tuonti korvaa nykyiset tiedot.","Tiedot viety (allekirjoitettu tiedosto)",
    "Tiedot tuotu onnistuneesti tiedostosta!","Virheellinen tiedostomuoto","Tiedoston lukeminen epäonnistui","Kieli vaihdettu","Valitse kieli",
    "Etsi kieltä...","Tuloksia ei löytynyt",
]

# Czech
TRANSLATIONS["cs"] = [
    "Svět Znalostí","AWESchool - Vzdělávací Hra","Vítejte","Zadejte své jméno","Začít se učit",
    "Nová registrace","Již mám účet — Obnovit","Interaktivní vzdělávací platforma: 200+ předmětů, 10 000+ lekcí, čtení hlasem, zkoušky.","Obnovit z JSON souboru","Vyberte si postavu",
    "Vítejte","Vyberte předmět, učte se lekce, složte zkoušky","Hlavní předměty","Vědy","Humanitní předměty",
    "Počítačové profese","Pokročilé technologie","Poslouchat","Stop","Další",
    "Předchozí","Začít zkoušku","lekcí","dokončeno","Získat nápovědu",
    "Vysvětlení","Otázka","Zkontrolovat","Konec","Gratulujeme",
    "Zkuste to znovu","Úspěšně jste složil zkoušku","Potřebujete 60%+ pro další lekci","Dokončené lekce","Počet dní v řadě",
    "Body","Moje statistiky","Úspěchy","Naučeno","Oblíbené",
    "Záložky","Nastavení","Téma","Světlé","Tmavé",
    "Auto","Velikost písma","Malé","Střední","Velké",
    "Denní cíl","Jazyk","Výchozí režim učení","Tmavé téma je lepší pro večerní studium. Velké písmo pro zrak.","Škola",
    "Univerzita","Snadné lekce, barevné a interaktivní","Detailní kniha, 100+ stran, s testy","Průvodci","Jak používat web",
    "Jak začít","První kroky na webu","Škola a Univerzita","Dva režimy učení","Poslouchat lekce",
    "Čtení hlasem","Sdílet statistiky","Pošlete svůj pokrok přátelům","Export / Import","Zálohování dat na soubory",
    "200+ jazyků","Změnit jazyk webu","Úspěchy","Soutěžte s ostatními účastníky","Všichni průvodci",
    "Domů","Živé demo","Krok","EXPORT","IMPORT",
    "Můj profil","Sdílet profil","Hledat lekce...","Vše","Dokončeno",
    "Dostupné","Uzamčeno","Oblíbené","Denní cíl","Nedávno zhlédnuté",
    "Pokračovat v učení","Začít znovu","Sdílet data","Předměty","Moje úspěchy",
    "Jste si jistý, že chcete smazat všechen pokrok?","🎉 Gratulujeme! Dnešní cíl splněn!","Zbývá {n} lekcí do dnešního cíle","Kniha","Kapitola",
    "Strana","Test","Hranice prospěšnosti: 51%","Další kapitola","© AWESchool Všechna práva vyhrazena",
    "Učte se, hrajte, rostěte","Statistiky","Dokončené lekce","Počet dní v řadě","Body",
    "Úspěchy","Celkem lekcí","Čas studia","Vytváří se snímek...","Statistiky zkopírovány!",
    "Sdílet statistiky","Hlas funguje přes Google TTS","Aktuální engine","Otestovat hlas","Vybrat hlas",
    "Rychlost","Výška","Hlasitost","Text čte Google TTS (zdarma","Export / import dat",
    "Stáhněte všechna data jako podepsaný JSON soubor","Obnovte data z dříve exportovaného souboru","Soubory jsou podepsány AWESchool. Padělané soubory budou odmítnuty.","Import nahradí aktuální data.","Data exportována (podepsaný soubor)",
    "Data úspěšně importována ze souboru!","Neplatný formát souboru","Čtení souboru selhalo","Jazyk změněn","Vybrat jazyk",
    "Hledat jazyk...","Nebyly nalezeny žádné výsledky",
]

# Greek
TRANSLATIONS["el"] = [
    "Κόσμος της Γνώσης","AWESchool - Εκπαιδευτικό Παιχνίδι","Καλώς ήρθατε","Εισάγετε το όνομά σας","Ξεκινήστε να μαθαίνετε",
    "Νέα εγγραφή","Έχω ήδη λογαριασμό — Επαναφορά","Διαδραστική εκπαιδευτική πλατφόρμα: 200+ μαθήματα, 10.000+ μαθήματα, φωνητική ανάγνωση, εξετάσεις.","Επαναφορά από αρχείο JSON","Επιλέξτε τον χαρακτήρα σας",
    "Καλώς ήρθατε","Επιλέξτε ένα μάθημα, μάθετε μαθήματα, περάστε εξετάσεις","Κύρια μαθήματα","Επιστήμες","Ανθρωπιστικές επιστήμες",
    "Επαγγέλματα υπολογιστών","Προηγμένες τεχνολογίες","Ακούστε","Διακοπή","Επόμενο",
    "Προηγούμενο","Έναρξη εξέτασης","μαθήματα","ολοκληρωμένα","Λάβετε υπόδειξη",
    "Εξήγηση","Ερώτηση","Έλεγχος","Έξοδος","Συγχαρητήρια",
    "Δοκιμάστε ξανά","Περάσατε την εξέταση επιτυχώς","Απαιτείται 60%+ για το επόμενο μάθημα","Ολοκληρωμένα μαθήματα","Συνεχόμενες ημέρες",
    "Πόντοι","Τα στατιστικά μου","Επιτεύγματα","Μελετήθηκε","Αγαπημένα",
    "Σελιδοδείκτες","Ρυθμίσεις","Θέμα","Φωτεινό","Σκοτεινό",
    "Αυτόματο","Μέγεθος γραμματοσειράς","Μικρό","Μεσαίο","Μεγάλο",
    "Ημερήσιος στόχος","Γλώσσα","Προεπιλεγμένη λειτουργία μάθησης","Το σκοτεινό θέμα είναι καλύτερο για βραδινή μελέτη. Μεγάλη γραμματοσειρά για την όραση.","Σχολείο",
    "Πανεπιστήμιο","Εύκολα μαθήματα, πολύχρωμα και διαδραστικά","Λεπτομερές βιβλίο, 100+ σελίδες, με τεστ","Οδηγοί","Πώς να χρησιμοποιήσετε τον ιστότοπο",
    "Πώς να ξεκινήσετε","Πρώτα βήματα στον ιστότοπο","Σχολείο και Πανεπιστήμιο","Δύο λειτουργίες μάθησης","Ακούστε μαθήματα",
    "Φωνητική ανάγνωση","Κοινοποίηση στατιστικών","Στείλτε την πρόοδό σας σε φίλους","Εξαγωγή / Εισαγωγή","Αντίγραφο ασφαλείας βάσει αρχείων",
    "200+ γλώσσες","Αλλαγή γλώσσας ιστότοπου","Επιτεύγματα","Ανταγωνιστείτε με άλλους συμμετέχοντες","Όλοι οι οδηγοί",
    "Αρχική","Ζωντανή επίδειξη","Βήμα","ΕΞΑΓΩΓΗ","ΕΙΣΑΓΩΓΗ",
    "Το προφίλ μου","Κοινοποίηση προφίλ","Αναζήτηση μαθημάτων...","Όλα","Ολοκληρωμένα",
    "Διαθέσιμα","Κλειδωμένα","Αγαπημένα","Ημερήσιος στόχος","Πρόσφατα προβληθέντα",
    "Συνέχεια μάθησης","Έναρξη εκ νέου","Κοινοποίηση δεδομένων","Μαθήματα","Τα επιτεύγματά μου",
    "Είστε σίγουροι ότι θέλετε να διαγράψετε όλη την πρόοδο;","🎉 Συγχαρητήρια! Ο σημερινός στόχος επιτεύχθηκε!","Απομένουν {n} μαθήματα για τον σημερινό στόχο","Βιβλίο","Κεφάλαιο",
    "Σελίδα","Τεστ","Όριο επιτυχίας: 51%","Επόμενο κεφάλαιο","© AWESchool Με επιφύλαξη κάθε δικαιώματος",
    "Μάθε, παίξε, αναπτυχσου","Στατιστικά","Ολοκληρωμένα μαθήματα","Συνεχόμενες ημέρες","Πόντοι",
    "Επιτεύγματα","Σύνολο μαθημάτων","Χρόνος μελέτης","Δημιουργία στιγμιότυπου...","Τα στατιστικά αντιγράφηκαν!",
    "Κοινοποίηση στατιστικών","Η φωνή λειτουργεί μέσω Google TTS","Τρέχων μηχανισμός","Δοκιμή φωνής","Επιλογή φωνής",
    "Ταχύτητα","Τόνος","Ένταση","Το κείμενο διαβάζεται από Google TTS (δωρεάν","Εξαγωγή / εισαγωγή δεδομένων",
    "Κατεβάστε όλα τα δεδομένα σας ως υπογεγραμμένο αρχείο JSON","Επαναφέρετε τα δεδομένα σας από προηγουμένως εξαγόμενο αρχείο","Τα αρχεία υπογράφονται από AWESchool. Πλαστά αρχεία θα απορρίφθηκαν.","Η εισαγωγή θα αντικαταστήσει τα τρέχοντα δεδομένα.","Δεδομένα εξήχθησαν (υπογεγραμμένο αρχείο)",
    "Τα δεδομένα εισήχθησαν επιτυχώς από αρχείο!","Μη έγκυρη μορφή αρχείου","Αποτυχία ανάγνωσης αρχείου","Η γλώσσα άλλαξε","Επιλογή γλώσσας",
    "Αναζήτηση γλώσσας...","Δεν βρέθηκαν αποτελέσματα",
]

# Hebrew
TRANSLATIONS["he"] = [
    "עולם הידע","AWESchool - משחק חינוכי","ברוכים הבאים","הזן את שמך","התחל ללמוד",
    "הרשמה חדשה","כבר יש לי חשבון — שחזר","פלטפורמת חינוך אינטראקטיבית: 200+ מקצועות, 10,000+ שיעורים, קריאה בקול, בחינות.","שחזר מקובץ JSON","בחר את הדמות שלך",
    "ברוכים הבאים","בחר מקצוע, למד שיעורים, עבור בחינות","מקצועות עיקריים","מדעים","מדעי הרוח",
    "מקצועות מחשב","טכנולוגיות מתקדמות","הקשב","עצור","הבא",
    "הקודם","התחל בחינה","שיעורים","הושלמו","קבל רמז",
    "הסבר","שאלה","בדוק","יציאה","ברכות",
    "נסה שוב","עברת את הבחינה בהצלחה","צריך 60%+ לשיעור הבא","שיעורים שהושלמו","ימים רצופים",
    "נקודות","הסטטיסטיקה שלי","הישגים","נלמד","מועדפים",
    "סימניות","הגדרות","ערכת נושא","בהיר","כהה",
    "אוטומטי","גודל גופן","קטן","בינוני","גדול",
    "יעד יומי","שפה","מצב למידה ברירת מחדל","ערכת נושא כהה טובה יותר ללימודי ערב. גופן גדול לראייה.","בית ספר",
    "אוניברסיטה","שיעורים קלים, צבעוני ואינטראקטיבי","ספר מפורט, 100+ עמודים, עם מבחנים","מדריכים","כיצד להשתמש באתר",
    "איך מתחילים","הצעדים הראשונים באתר","בית ספר ואוניברסיטה","שני מצבי למידה","הקשב לשיעורים",
    "קריאה בקול","שתף סטטיסטיקה","שלח את ההתקדמות שלך לחברים","ייצוא / ייבוא","גיבוי נתונים מבוסס קבצים",
    "200+ שפות","שנה את שפת האתר","הישגים","תחרות עם משתתפים אחרים","כל המדריכים",
    "בית","הדגמה חיה","שלב","ייצוא","ייבוא",
    "הפרופיל שלי","שתף פרופיל","חפש שיעורים...","הכל","הושלם",
    "זמין","נעול","מועדפים","יעד יומי","נצפו לאחרונה",
    "המשך ללמוד","התחל מחדש","שתף נתונים","מקצועות","ההישגים שלי",
    "האם אתה בטוח שברצונך למחוק את כל ההתקדמות?","🎉 ברכות! היעד היומי הושג!","נשארו {n} שיעורים ליעד היומי","ספר","פרק",
    "עמוד","מבחן","סף מעבר: 51%","הפרק הבא","© AWESchool כל הזכויות שמורות",
    "למד, שחק, צמח","סטטיסטיקה","שיעורים שהושלמו","ימים רצופים","נקודות",
    "הישגים","סך כל השיעורים","זמן למידה","יוצר צילום מסך...","הסטטיסטיקה הועתקה!",
    "שתף סטטיסטיקה","הקול עובד דרך Google TTS","מנוע נוכחי","בדוק קול","בחר קול",
    "מהירות","גובה צליל","עוצמת קול","הטקסט נקרא על ידי Google TTS (בחינם","ייצוא / ייבוא נתונים",
    "הורד את כל הנתונים שלך כקובץ JSON חתום","שחזר את הנתונים שלך מקובץ שיוצא קודם","קבצים נחתמים על ידי AWESchool. קבצים מזויפים יידחו.","הייבוא יחליף את הנתונים הנוכחיים.","הנתונים יוצאו (קובץ חתום)",
    "הנתונים יובאו בהצלחה מקובץ!","פורמט קובץ לא תקין","נכשל בקריאת הקובץ","השפה השתנתה","בחר שפה",
    "חפש שפה...","לא נמצאו תוצאות",
]

# Hungarian
TRANSLATIONS["hu"] = [
    "Tudás Világa","AWESchool - Oktatási Játék","Üdvözöljük","Adja meg a nevét","Tanulás kezdése",
    "Új regisztráció","Már van fiókom — Visszaállítás","Interaktív oktatási platform: 200+ tantárgy, 10.000+ lecke, hangos felolvasás, vizsgák.","Visszaállítás JSON fájlból","Válassza karakterét",
    "Üdvözöljük","Válasszon tantárgyat, tanuljon leckéket, menjen át vizsgákon","Fő tantárgyak","Tudományok","Humán tudományok",
    "Számítógépes szakmák","Fejlett technológiák","Hallgatás","Stop","Következő",
    "Előző","Vizsga kezdése","lecke","befejezett","Tipp kérése",
    "Magyarázat","Kérdés","Ellenőrzés","Kilépés","Gratulálunk",
    "Próbálja újra","Sikeresen átmegy a vizsgán","60%+ szükséges a következő leckéhez","Befejezett leckék","Egymást követő napok",
    "Pontok","Statisztikáim","Eredmények","Tanult","Kedvencek",
    "Könyvjelzők","Beállítások","Téma","Világos","Sötét",
    "Auto","Betűméret","Kicsi","Közepes","Nagy",
    "Napi cél","Nyelv","Alapértelmezett tanulási mód","A sötét téma jobb az esti tanuláshoz. Nagy betű a látásnak.","Iskola",
    "Egyetem","Könnyű leckék, színes és interaktív","Részletes könyv, 100+ oldal, tesztekkel","Útmutatók","Hogyan használja az oldalt",
    "Hogyan kezdje el","Első lépések az oldalon","Iskola és Egyetem","Két tanulási mód","Leckék hallgatása",
    "Hangos felolvasás","Statisztika megosztása","Küldje el előrehaladását barátainak","Exportálás / Importálás","Fájlalapú adatmentés",
    "200+ nyelv","Oldal nyelvének megváltoztatása","Eredmények","Versenyezzen más résztvevőkkel","Minden útmutató",
    "Főoldal","Élő demó","Lépés","EXPORTÁLÁS","IMPORTÁLÁS",
    "Profilom","Profil megosztása","Leckék keresése...","Összes","Befejezett",
    "Elérhető","Zárolt","Kedvencek","Napi cél","Nemrég nézett",
    "Tanulás folytatása","Kezdje újra","Adatok megosztása","Tantárgyak","Eredményeim",
    "Biztosan törölni szeretné az összes előrehaladást?","🎉 Gratulálunk! A mai cél elérve!","{n} lecke van hátra a mai célig","Könyv","Fejezet",
    "Oldal","Teszt","Átmeneti küszöb: 51%","Következő fejezet","© AWESchool Minden jog fenntartva",
    "Tanulj, játssz, növekedj","Statisztika","Befejezett leckék","Egymást követő napok","Pontok",
    "Eredmények","Összes lecke","Tanulási idő","Képernyőkép létrehozása...","Statisztika másolva!",
    "Statisztika megosztása","A hang a Google TTS-en keresztül működik","Jelenlegi motor","Hang tesztelése","Hang kiválasztása",
    "Sebesség","Hangmagasság","Hangerő","A szöveget a Google TTS olvassa (ingyenes","Adat exportálás / importálás",
    "Töltse le az összes adatát aláírt JSON fájlként","Állítsa vissza adatait egy korábban exportált fájlból","A fájlokat az AWESchool írja alá. Hamisított fájlokat elutasítják.","Az importálás felváltja a jelenlegi adatokat.","Adatok exportálva (aláírt fájl)",
    "Adatok sikeresen importálva fájlból!","Érvénytelen fájlformátum","Nem sikerült olvasni a fájlt","Nyelv megváltozott","Nyelv kiválasztása",
    "Nyelv keresése...","Nem találhatók eredmények",
]

# Romanian
TRANSLATIONS["ro"] = [
    "Lumea Cunoașterii","AWESchool - Joc Educațional","Bun venit","Introduceți numele dumneavoastră","Începeți să învățați",
    "Înregistrare nouă","Am deja un cont — Restaurează","Platformă educațională interactivă: 200+ materii, 10.000+ lecții, citire vocală, examene.","Restaurează din fișier JSON","Alegeți personajul",
    "Bun venit","Alegeți o materie, învățați lecții, treceți examenele","Materii principale","Științe","Științe umaniste",
    "Profesii informatice","Tehnologii avansate","Ascultă","Oprește","Următorul",
    "Anterior","Începe examenul","lecții","finalizate","Obține indiciu",
    "Explicație","Întrebare","Verifică","Ieșire","Felicitări",
    "Încercați din nou","Ați promovat examenul","Necesită 60%+ pentru lecția următoare","Lecții finalizate","Zile consecutive",
    "Puncte","Statisticile mele","Realizări","Studiat","Favorite",
    "Semne de carte","Setări","Temă","Luminoasă","Întunecată",
    "Auto","Mărime font","Mic","Mediu","Mare",
    "Obiectiv zilnic","Limbă","Mod de învățare implicit","Tema întunecată este mai bună pentru studiul de seară. Font mare pentru vedere.","Școală",
    "Universitate","Lecții ușoare, colorat și interactiv","Carte detaliată, 100+ pagini, cu teste","Ghiduri","Cum se folosește site-ul",
    "Cum se începe","Primii pași pe site","Școală și Universitate","Două moduri de învățare","Ascultă lecțiile",
    "Citire vocală","Distribuie statistici","Trimiteți progresul dvs. prietenilor","Export / Import","Backup de date bazat pe fișiere",
    "200+ limbi","Schimbă limba site-ului","Realizări","Concurați cu alți participanți","Toate ghidurile",
    "Acasă","Demo live","Pas","EXPORTĂ","IMPORTĂ",
    "Profilul meu","Distribuie profil","Caută lecții...","Toate","Finalizate",
    "Disponibile","Blocate","Favorite","Obiectiv zilnic","Văzute recent",
    "Continuă să înveți","Începe din nou","Distribuie date","Materii","Realizările mele",
    "Sunteți sigur că doriți să ștergeți tot progresul?","🎉 Felicitări! Obiectivul de azi a fost atins!","Mai sunt {n} lecții până la obiectivul de azi","Carte","Capitol",
    "Pagină","Test","Prag de promovare: 51%","Capitolul următor","© AWESchool Toate drepturile rezervate",
    "Învață, joacă, crește","Statistici","Lecții finalizate","Zile consecutive","Puncte",
    "Realizări","Total lecții","Timp de studiu","Se creează captura de ecran...","Statistici copiate!",
    "Distribuie statistici","Vocea funcționează prin Google TTS","Motor curent","Testează vocea","Selectează vocea",
    "Viteză","Ton","Volum","Textul este citit de Google TTS ( gratuit","Export / import de date",
    "Descărcați toate datele ca fișier JSON semnat","Restaurați-vă datele dintr-un fișier exportat anterior","Fișierele sunt semnate de AWESchool. Fișierele falsificate vor fi respinse.","Importul va înlocui datele curente.","Date exportate (fișier semnat)",
    "Date importate cu succes din fișier!","Format de fișier invalid","Citirea fișierului a eșuat","Limba a fost schimbată","Selectează limba",
    "Caută limba...","Nu s-au găsit rezultate",
]

# Bulgarian
TRANSLATIONS["bg"] = [
    "Свят на Знания","AWESchool - Образователна Игра","Добре дошли","Въведете вашето име","Започнете да учите",
    "Нова регистрация","Вече имам профил — Възстанови","Интерактивна образователна платформа: 200+ предмета, 10 000+ урока, гласово четене, изпити.","Възстанови от JSON файл","Изберете своя герой",
    "Добре дошли","Изберете предмет, учете уроци, вземете изпити","Основни предмети","Науки","Хуманитарни науки",
    "Компютърни професии","Напреднали технологии","Слушай","Стоп","Следващ",
    "Предишен","Започни изпит","урока","завършени","Получи подсказка",
    "Обяснение","Въпрос","Провери","Изход","Поздравления",
    "Опитайте отново","Успешно издържахте изпита","Нужно е 60%+ за следващия урок","Завършени уроци","Дни подред",
    "Точки","Моята статистика","Постижения","Учено","Любими",
    "Отметки","Настройки","Тема","Светла","Тъмна",
    "Авто","Размер на шрифта","Малък","Среден","Голям",
    "Дневна цел","Език","Режим на обучение по подразбиране","Тъмната тема е по-добра за вечерно учене. Голям шрифт за зрението.","Училище",
    "Университет","Лесни уроци, цветно и интерактивно","Подробна книга, 100+ страници, с тестове","Ръководства","Как да използвате сайта",
    "Как да започнете","Първи стъпки в сайта","Училище и Университет","Два режима на обучение","Слушайте уроците",
    "Гласово четене","Споделете статистика","Изпратете напредъка си на приятели","Експорт / Импорт","Архивиране на данни на файлове",
    "200+ езика","Промяна на езика на сайта","Постижения","Състезавайте се с други участници","Всички ръководства",
    "Начало","Жива демонстрация","Стъпка","ЕКСПОРТ","ИМПОРТ",
    "Моят профил","Сподели профил","Търсене на уроци...","Всички","Завършени",
    "Налични","Заключени","Любими","Дневна цел","Наскоро разгледани",
    "Продължете обучението","Започнете отначало","Сподели данни","Предмети","Моите постижения",
    "Сигурни ли сте, че искате да изтриете целия напредък?","🎉 Поздравления! Дневната цел е постигната!","Остават {n} урока до днешната цел","Книга","Глава",
    "Страница","Тест","Праг за преминаване: 51%","Следваща глава","© AWESchool Всички права запазени",
    "Учете, играйте, растете","Статистика","Завършени уроци","Дни подред","Точки",
    "Постижения","Общо уроци","Време за учене","Създава се снимка на екрана...","Статистиката е копирана!",
    "Сподели статистика","Гласът работи чрез Google TTS","Текущ двигател","Тествай глас","Избери глас",
    "Скорост","Височина","Сила на звука","Текстът се чете от Google TTS ( безплатно","Експорт / импорт на данни",
    "Изтеглете всичките си данни като подписан JSON файл","Възстановете данните си от предварително експортиран файл","Файловете са подписани от AWESchool. Фалшиви файлове ще бъдат отхвърлени.","Импортът ще замени текущите данни.","Данните са експортирани (подписан файл)",
    "Данните са успешно импортирани от файл!","Невалиден формат на файла","Четенето на файла не бе успешно","Езикът е променен","Избери език",
    "Търсене на език...","Не са намерени резултати",
]

# Generate
def quote(s):
    s = s.replace("\\","\\\\").replace("'","\\'")
    return f"'{s}'"

for code, values in TRANSLATIONS.items():
    assert len(values) == len(KEYS), f"{code}: expected {len(KEYS)} values, got {len(values)}"
    lines = []
    lines.append(f"// {code} - UI translations (hand-curated)")
    lines.append("")
    lines.append(f"export const {code}: Record<string, string> = {{")
    for k, v in zip(KEYS, values):
        lines.append(f"  {quote(k)}: {quote(v)},")
    lines.append("}")
    lines.append("")
    (OUT_DIR / f"{code}.ts").write_text("\n".join(lines), encoding="utf-8")
    print(f"  ✓ {code}.ts ({len(values)} keys)")

print(f"\n✓ Generated {len(TRANSLATIONS)} more hand-curated translation files")
